### ISSUE TITLE
Coding path: Guilds

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#15]
Гильдиями называем объединение людей с общим техническим стеком. Основная идея - объединение людей, которые могут вместе что-то разрабатывать, взаимодействовать.

Для реализации требуется:

Бекенд:
1. [x] Страница обзора гильдий (#16)
2. [x] Профиль гильдии (#17)
3. [x] Механизм вступления (#18)
4. [x] Логика управления членами гильдии (#19)
5. [x] Управление гильдией (#20)
6. [x] Механизм создания гильдии (#21)

Фронт:
1. [x] Рейтинг гильдий (#73)
2. [x] Профиль гильдии (#39)
3. [x] Кнопки входа-выхода из гильдии (#72)
