### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by InRedikaWB** [kysect/iwentys#25]
Если мы хотим форсить идею с хакатонами - нам нужно будет как-то собираться информацию про проведение всех таких + наверное форма предложения хакатона, какая-то новостная лента с ними. Аналогичная ситуация для курсов, боткемпов

Задачи:
1. [ ] Добавление сущности "Event" в систему (#26)
2. [ ] Добавление логики создания события (#27)
3. [ ] Добавление возможности трекать список участников, а также делать запрос на добавления пользователя в участники (#28)
4. [ ] Набросать макет профиля события
5. [ ] Реализовать макет

**Comment by hrrrrustic** [comment]
Про какие хакатоны/курсы идет речь? Сторонние или кастомные, организацией которой тоже будете заниматься вы? Если сторонние, то непонятен пункт про добавление в участники. Планируется интеграция с организатором или подача заявки за человека?

**Comment by InRedikaWB** [comment]
@hrrrrustic  Изначально была и про свои, но это вылилось в отдельную фичу (турниры), теперь их нужно будет как-то подружить. Так что больно про сторонние. Под добавление подразумевается то, что студент сходил на хакатон, и чтобы его добавить в систему он должен закинуть заявку с пруфами.
