### ISSUE TITLE
Coding path: tributes

### ISSUE THREAD

**Issue by FrediKats** [kysect/iwentys#89]
Суть механики во взаимодействии студент-ментор по средствам оценки проектов.

Бекенд:
- [x] Механизм добавления, удаления и просмотра трибьютов (#90)
- [x] Механизм сохранения ревью от тотема 
- [x] Добавление информации о текущем трибьюте в профиль гильдии
- [ ] Учитывание трибьютов в рейтинге участников гильдии (#91)
- [ ] Добавить возможность получить список репозиториев доступных для отправки на трибьют (#92)
Фронт:
- [x] Добавить в UI профиля гильдии отображение информации о трибьюте (#93)
- [x] Добавить страницу отображения трибьютов гильдии (#94 )
- [ ] Добавить вью для выбора репозитория для отправки трибьюта (#95)
- [ ] Добавить вью для загрузки фидбека по трибьюту (#96)

**Comment by FrediKats** [comment]
Вся логика работы с сектами уехала в Recademy. Обратно.
